# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add gcc musl-dev make pkgconf wget openssh-client mbedtls-dev zlib-dev
WORKDIR /build
RUN git clone https://github.com/shirok/Gauche.git gauche --depth 1 --tags
WORKDIR /build/gauche
RUN ./configure
RUN make
RUN make install

FROM alpine
RUN apk add mbedtls
COPY --from=build /usr/local/ /usr/local/
COPY scheme-banner scheme-eval /usr/local/bin/
RUN ln -s gosh /usr/bin/scheme-r7rs
CMD ["scheme-banner"]
