# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add git rust cargo
WORKDIR /build
RUN git clone https://github.com/mattwparas/steel.git --depth=1
WORKDIR /build/steel
RUN cargo install --path=. --root=/usr/other

FROM alpine
COPY --from=build /usr/other/ /usr/local/
RUN apk add lld
ENV PATH=/usr/local/capy/0.1.0:${PATH}
COPY scheme-banner /usr/local/bin/
RUN mkdir -p /root/.local/share/steel
CMD scheme-banner
