# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add git make gcc musl-dev
WORKDIR /build
RUN git clone https://github.com/ashinn/chibi-scheme.git chibi --depth 1
WORKDIR /build/chibi
RUN make
#RUN make test-dist
RUN make install

FROM alpine
COPY --from=build /usr/local/ /usr/local/
COPY scheme-banner /usr/local/bin/
COPY scheme-r7rs /usr/local/bin/
CMD ["scheme-banner"]
