(define-library (scheme-docker-lib)
  (export os-implementation-dockerfile)
  (import (scheme base)
          (scheme read)
          (scheme write)
          (srfi 1)
          (srfi 132)
          (lassik unpack-assoc)
          (lassik dockerfile))
  (cond-expand (chibi (import (srfi 130)))
               (gauche (import (srfi 13))))
  (include "scheme-docker-lib.scm"))
