FROM fedora:latest
ARG BANNER
ADD scheme.tar.gz /
RUN echo "#!/bin/sh" > /usr/local/bin/scheme-banner && chmod +x /usr/local/bin/scheme-banner
RUN echo "$BANNER" >> /usr/local/bin/scheme-banner
ENV PATH=/opt/gnu/bin:${PATH}
CMD ["scheme-banner"]
