# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add gcc musl-dev mingw-w64-gcc gcompat rsync bison flex git
WORKDIR /build
RUN git clone https://github.com/rnvannatta/vanity-scheme.git vanity --depth 1
WORKDIR /build/vanity
RUN ./configure --prefix=/usr/local
RUN make hatch
RUN make all -j
RUN make install

FROM alpine
COPY --from=build /usr/local/ /usr/local/
#COPY scheme-banner /usr/local/bin/
#CMD ["scheme-banner"]
