# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add llvm15-dev llvm15-libs gcc musl-dev git xz cmake make g++
WORKDIR /build/
RUN git clone https://github.com/fujita-y/ypsilon.git --depth 1
WORKDIR /build/ypsilon
RUN cmake -DCMAKE_BUILD_TYPE=Release .
RUN cmake --build .
RUN cmake --install .

FROM alpine
RUN apk add llvm15-libs
COPY --from=build /usr/local/ /usr/local/
COPY scheme-script /usr/local/bin
RUN ln -s ypsilon /usr/local/bin/scheme-banner
CMD ["scheme-banner"]
