# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine:3.23 AS build
RUN apk add musl-dev make git clang
WORKDIR /build
RUN git clone https://github.com/false-schemers/skint.git --depth=1
WORKDIR /build/skint
RUN sh configure --prefix=/usr/local
RUN make
RUN make test
RUN make install
RUN make libtest
RUN make libinstall

FROM alpine
COPY --from=build /usr/local/ /usr/local/
RUN ln -s skint /usr/local/bin/scheme-banner \
 && ln -s skint /usr/local/bin/scheme-r7rs
CMD ["scheme-banner"]
