# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine:3.23 AS build
RUN apk add build-base wget
WORKDIR /build
RUN git clone https://github.com/uim/sigscheme.git --depth=1
WORKDIR /build/sigscheme
RUN ./configure
RUN make
RUN make install

FROM alpine
COPY --from=build /usr/local/ /usr/local/
COPY scheme-banner /usr/local/bin/scheme-banner
CMD ["scheme-banner"]

