# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add cmake gmp-dev clang git make
WORKDIR /build
RUN git clone https://github.com/yamacir-kit/meevax.git --depth=1
WORKDIR /build/meevax
RUN cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
WORKDIR /build/meevax/build
RUN make all
RUN make install

FROM alpine
RUN apk add gmp libstdc++
COPY --from=build /usr/local/ /usr/local/
COPY scheme-banner /usr/local/bin/
CMD ["scheme-banner"]
