# -*- mode: dockerfile; coding: utf-8 -*-
FROM rust:alpine AS build
RUN apk add make libffi-dev clang rsync git musl-dev gcompat bash
WORKDIR /build
RUN git clone https://github.com/playX18/capyscheme.git --depth=1
WORKDIR /build/capyscheme
RUN make PREFIX=/usr/other
RUN make PREFIX=/usr/other install

FROM alpine
COPY --from=build /usr/other/ /usr/other/
ENV PATH=/usr/other/bin:${PATH}
COPY scheme-banner /usr/local/bin/
CMD ["scheme-banner"]
