# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine
RUN apk add nodejs npm git
WORKDIR /build
RUN git clone https://github.com/biwascheme/biwascheme.git
WORKDIR /build/biwascheme
RUN npm install
RUN npm run build
RUN npm pack
RUN npm -g install biwascheme*.tgz
RUN ln -s biwas /usr/local/bin/scheme-banner
CMD ["scheme-banner"]
