FROM alpine AS build
RUN apk add gcc make musl-dev sqlite-dev openssl-dev zlib-dev git
WORKDIR /build
RUN git clone https://github.com/mighty-gerbils/gerbil.git
WORKDIR /build/gerbil
RUN ./configure
RUN make -j8
RUN make install

FROM alpine
RUN apk add gcc musl-dev
COPY --from=build /opt/gerbil /opt/gerbil
ENV PATH=/opt/gerbil/bin:${PATH}
RUN ln -s /opt/gerbil/bin/gxi /usr/local/bin/scheme-banner
CMD ["scheme-banner"]
