# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add git make gcc musl-dev gc-dev
WORKDIR /build
RUN git clone https://github.com/ashinn/chibi-scheme.git snow-chibi --depth 1
WORKDIR /build/snow-chibi
RUN make PREFIX=/opt/snow-chibi
RUN make PREFIX=/opt/snow-chibi install

FROM alpine
COPY --from=build /opt /opt
ENV PATH=/opt/snow-chibi/bin:${PATH}
ENV LD_LIBRARY_PATH=/opt/snow-chibi/lib
