# -*- mode: dockerfile; coding: utf-8 -*-
FROM rust:alpine AS build
RUN apk add git
WORKDIR /build
RUN git clone https://github.com/raviqqe/stak.git --depth=1
WORKDIR /build/stak
#RUN cargo build
RUN cargo install stak --root /usr/local

FROM alpine
COPY --from=build /usr/local/ /usr/local/
COPY scheme-banner /usr/local/bin/
RUN ldconfig
CMD scheme-banner
