# -*- mode: dockerfile; coding: utf-8 -*-
FROM rust:alpine AS build
RUN apk add git
WORKDIR /build
RUN git clone https://github.com/raviqqe/stak.git --depth=1
WORKDIR /build/stak
RUN cargo install stak --root /usr/other

FROM alpine
COPY --from=build /usr/other/ /usr/other/
ENV PATH=/usr/other/bin:${PATH}
COPY scheme-banner /usr/local/bin/
CMD ["scheme-banner"]
