# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine
RUN apk add nodejs npm git
WORKDIR /build
RUN git clone https://github.com/jcubic/lips.git --depth=1
WORKDIR /build/lips
RUN npm install
RUN npm pack
RUN npm install -g lips*.tgz
RUN ln -s lips /usr/local/bin/scheme-banner \
 && ln -s lips /usr/local/bin/scheme-r7rs
CMD ["scheme-banner"]
