# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine:3.23 AS build
RUN apk add nodejs npm
WORKDIR /build
COPY checksum checksum
RUN wget -O lips.tgz \
    https://github.com/jcubic/lips/archive/refs/tags/1.0.0-beta.23.1.tar.gz
RUN sha256sum lips.tgz && sha256sum -c checksum
RUN mkdir lips && tar -C lips --strip-components 1 -xf lips.tgz
WORKDIR /build/lips
RUN npm install -g

FROM alpine
RUN apk add nodejs
COPY --from=build /usr/local/ /usr/local/
RUN ln -sf lips /usr/local/bin/scheme-banner \
 && ln -sf lips /usr/local/bin/scheme-r7rs
CMD ["scheme-banner"]
