# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add git
WORKDIR /build
RUN git clone https://github.com/justinethier/husk-scheme.git --depth=1
RUN apk add musl-dev gcc cabal git ncurses-dev libffi-dev
WORKDIR /build/husk-scheme
RUN cabal update
RUN cabal build
RUN cabal install

FROM alpine
RUN apk add libffi
COPY --from=build /root/.cabal /root/.cabal
ENV PATH=/root/.cabal/bin:${PATH}
RUN ln -s /root/.cabal/bin/huski /usr/local/bin/scheme-banner
CMD ["scheme-banner"]
