# -*- mode: dockerfile; coding: utf-8 -*-
FROM alpine AS build
RUN apk add gcc musl-dev make git
WORKDIR /build
RUN git clone https://github.com/lambdaconservatory/xscheme.git --depth 1
WORKDIR /build/xscheme
RUN make
RUN cp xscheme /usr/local/bin/xscheme

FROM alpine
COPY --from=build /usr/local/ /usr/local/
RUN ln -s xscheme /usr/local/bin/scheme-banner
CMD ["scheme-banner"]
