name: docker-conscheme-push-action

on:
  push:
    paths:
      - implementations/conscheme/**/Dockerfile*
      - .github/workflows/conscheme*.yml
jobs:
  Debian-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/conscheme latest
        run: make VERSION=latest SCHEME=conscheme build
      - name: Push schemers/conscheme latest
        if: github.ref == 'refs/heads/master'
        run: make VERSION=latest SCHEME=conscheme push
  Debian-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/conscheme head
        run: make VERSION=head SCHEME=conscheme build
      - name: Push schemers/conscheme head
        if: github.ref == 'refs/heads/master'
        run: make VERSION=head SCHEME=conscheme push
  Alpine-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/conscheme latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=conscheme build
      - name: Push schemers/conscheme latest alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=latest SCHEME=conscheme push
  Alpine-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/conscheme head alpine
        run: make LINUX=alpine VERSION=head SCHEME=conscheme build
      - name: Push schemers/conscheme head alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=head SCHEME=conscheme push
