name: cyclone

on:
  push:
    paths:
      - implementations/cyclone/**/Dockerfile*
      - .github/workflows/cyclone*.yml
  schedule: 
    - cron: "17 4 * * 2"
jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest
        run: make VERSION=latest SCHEME=cyclone build
      - name: Build schemers/cyclone head
        run: make VERSION=head SCHEME=cyclone build
  build-debian-arm:
    runs-on: ubuntu-latest-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest
        run: make VERSION=latest SCHEME=cyclone build
      - name: Build schemers/cyclone head
        run: make VERSION=head SCHEME=cyclone build
  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=cyclone build
      - name: Build schemers/cyclone head alpine
        run: make LINUX=alpine VERSION=head SCHEME=cyclone build
  build-alpine-arm:
    runs-on: ubuntu-latest-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=cyclone build
      - name: Build schemers/cyclone head alpine
        run: make LINUX=alpine VERSION=head SCHEME=cyclone build
  push-debian:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest
        run: make VERSION=latest SCHEME=cyclone build push
      - name: Build schemers/cyclone head
        run: make VERSION=head SCHEME=cyclone build push
  push-debian-arm:
    runs-on: ubuntu-latest-arm
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest
        run: make VERSION=latest SCHEME=cyclone build push
      - name: Build schemers/cyclone head
        run: make VERSION=head SCHEME=cyclone build push
  push-alpine:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=cyclone build push
      - name: Build schemers/cyclone head alpine
        run: make LINUX=alpine VERSION=head SCHEME=cyclone build push
  push-alpine-arm:
    runs-on: ubuntu-latest-arm
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/cyclone latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=cyclone build push
      - name: Build schemers/cyclone head alpine
        run: make LINUX=alpine VERSION=head SCHEME=cyclone build push
