name: docker-ironscheme-push-action

on:
  push:
    paths:
      - implementations/ironscheme/**/Dockerfile*
      - .github/workflows/ironscheme*.yml
  schedule:
    - cron: "17 4 * * 2"

jobs:
  build:
    strategy:
      matrix:
      implementation: ironscheme
      os: [ubuntu-25.04, ubuntu-24.04-arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build schemers/ironscheme latest
        run: make VERSION=latest SCHEME=ironscheme build
      - name: Build schemers/ironscheme latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=ironscheme build
      - name: Build schemers/ironscheme head
        run: make VERSION=head SCHEME=ironscheme build
      - name: Build schemers/ironscheme head alpine
        run: make LINUX=alpine VERSION=head SCHEME=ironscheme build
