name: docker-jazz-push-action

on:
  push:
    paths:
      - implementations/jazz/**/Dockerfile*
      - .github/workflows/jazz*.yml
jobs:
  Debian-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/jazz latest
        run: make VERSION=latest SCHEME=jazz build
      - name: Push schemers/jazz latest
        if: github.ref == 'refs/heads/master'
        run: make VERSION=latest SCHEME=jazz push
  Debian-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/jazz head
        run: make VERSION=head SCHEME=jazz build
      - name: Push schemers/jazz head
        if: github.ref == 'refs/heads/master'
        run: make VERSION=head SCHEME=jazz push
  Alpine-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/jazz latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=jazz build
      - name: Push schemers/jazz latest alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=latest SCHEME=jazz push
  Alpine-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/jazz head alpine
        run: make LINUX=alpine VERSION=head SCHEME=jazz build
      - name: Push schemers/jazz head alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=head SCHEME=jazz push
