name: docker-rscheme-push-action

on:
  push:
    paths:
      - implementations/rscheme/**/Dockerfile*
      - .github/workflows/rscheme*.yml
jobs:
  Debian-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/rscheme latest
        run: make VERSION=latest SCHEME=rscheme build
      - name: Push schemers/rscheme latest
        if: github.ref == 'refs/heads/master'
        run: make VERSION=latest SCHEME=rscheme push
  Debian-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/rscheme head
        run: make VERSION=head SCHEME=rscheme build
      - name: Push schemers/rscheme head
        if: github.ref == 'refs/heads/master'
        run: make VERSION=head SCHEME=rscheme push
  Alpine-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/rscheme latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=rscheme build
      - name: Push schemers/rscheme latest alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=latest SCHEME=rscheme push
  Alpine-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/rscheme head alpine
        run: make LINUX=alpine VERSION=head SCHEME=rscheme build
      - name: Push schemers/rscheme head alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=head SCHEME=rscheme push
