name: docker-sizzle-push-action

on:
  push:
    paths:
      - implementations/sizzle/**/Dockerfile*
      - .github/workflows/sizzle*.yml
jobs:
  Debian-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/sizzle latest
        run: make VERSION=latest SCHEME=sizzle build
      - name: Push schemers/sizzle latest
        if: github.ref == 'refs/heads/master'
        run: make VERSION=latest SCHEME=sizzle push
  Debian-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/sizzle head
        run: make VERSION=head SCHEME=sizzle build
      - name: Push schemers/sizzle head
        if: github.ref == 'refs/heads/master'
        run: make VERSION=head SCHEME=sizzle push
  Alpine-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/sizzle latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=sizzle build
      - name: Push schemers/sizzle latest alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=latest SCHEME=sizzle push
  Alpine-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/sizzle head alpine
        run: make LINUX=alpine VERSION=head SCHEME=sizzle build
      - name: Push schemers/sizzle head alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=head SCHEME=sizzle push
