name: docker-vx-push-action

on:
  push:
    paths:
      - implementations/vx/**/Dockerfile*
      - .github/workflows/vx*.yml
jobs:
  Debian-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/vx latest
        run: make VERSION=latest SCHEME=vx build
      - name: Push schemers/vx latest
        if: github.ref == 'refs/heads/master'
        run: make VERSION=latest SCHEME=vx push
  Debian-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/vx head
        run: make VERSION=head SCHEME=vx build
      - name: Push schemers/vx head
        if: github.ref == 'refs/heads/master'
        run: make VERSION=head SCHEME=vx push
  Alpine-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/vx latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=vx build
      - name: Push schemers/vx latest alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=latest SCHEME=vx push
  Alpine-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/vx head alpine
        run: make LINUX=alpine VERSION=head SCHEME=vx build
      - name: Push schemers/vx head alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=head SCHEME=vx push
