name: docker-xscheme-push-action

on:
  push:
    paths:
      - implementations/xscheme/**/Dockerfile*
      - .github/workflows/xscheme*.yml
jobs:
  Debian-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/xscheme latest
        run: make VERSION=latest SCHEME=xscheme build
      - name: Push schemers/xscheme latest
        if: github.ref == 'refs/heads/master'
        run: make VERSION=latest SCHEME=xscheme push
  Debian-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/xscheme head
        run: make VERSION=head SCHEME=xscheme build
      - name: Push schemers/xscheme head
        if: github.ref == 'refs/heads/master'
        run: make VERSION=head SCHEME=xscheme push
  Alpine-latest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/xscheme latest alpine
        run: make LINUX=alpine VERSION=latest SCHEME=xscheme build
      - name: Push schemers/xscheme latest alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=latest SCHEME=xscheme push
  Alpine-head:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build schemers/xscheme head alpine
        run: make LINUX=alpine VERSION=head SCHEME=xscheme build
      - name: Push schemers/xscheme head alpine
        if: github.ref == 'refs/heads/master'
        run: make LINUX=alpine VERSION=head SCHEME=xscheme push
